### PR TITLE
Fix door requiring two close commands to close

### PR DESCRIPTION
**Pull request by bdraco**
reported at https://github.com/home-assistant/core/issues/103336#issuecomment-1793613688 and confirmed locally

### CODE REVIEW

**Comment by bdraco** [comment]
```
[07:47:51][D][ratgdo:533]: Close door called, current state: OPEN
[07:47:51][D][ratgdo:554]: Sending close door, current state: OPEN
```

..nothing happens..

**Comment by bdraco** [comment]
second time it works

```
[07:48:26][D][cover:076]: 'Door' - Setting
[07:48:26][D][cover:084]:   Position: 0%
[07:48:26][D][ratgdo:533]: Close door called, current state: OPEN
[07:48:26][D][ratgdo:554]: Sending close door, current state: OPEN
[07:48:27][D][ratgdo:464]: Collision detected, waiting to send packet
[07:48:27][D][ratgdo:464]: Collision detected, waiting to send packet
[07:48:27][D][number:012]: 'Rolling code counter': Sending state 7853.000000
```

**Comment by bdraco** [comment]
```
[08:00:02][D][ratgdo:533]: Close door called, current state: OPEN
[08:00:02][D][ratgdo:554]: Sending close door, current state: OPEN
[08:00:02][D][ratgdo:624]: Door command press: 00010100
[08:00:02][D][ratgdo:628]: Door command release: 00010000
[08:00:02][D][number:012]: 'Rolling code counter': Sending state 7898.000000
```

I always seem to get the rolling code counter back on the first close and it doesn't work

**Comment by bdraco** [comment]
This is failure mode
```


[08:02:45][D][cover:076]: 'Door' - Setting
[08:02:45][D][cover:084]:   Position: 0%
[08:02:45][D][ratgdo:533]: Close door called, current state: OPEN
[08:02:45][D][ratgdo:554]: Sending close door, current state: OPEN
[08:02:45][D][ratgdo:624]: Door command press: 00010100
[08:02:45][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010100
[08:02:45][D][ratgdo:285]: [67759] Encode for transmit rolling=0001edf fixed=0200006b2a data=01010080
[08:02:45][D][ratgdo:471]: Sending packet
[08:02:45][W][component:214]: Component api took a long time for an operation (0.06 s).
[08:02:45][W][component:215]: Components should block for at most 20-30ms.
[08:02:45][D][ratgdo:628]: Door command release: 00010000
[08:02:45][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010000
[08:02:45][D][ratgdo:285]: [67913] Encode for transmit rolling=0001edf fixed=0200006b2a data=01000080
[08:02:45][D][ratgdo:471]: Sending packet
[08:02:45][D][number:012]: 'Rolling code counter': Sending state 7904.000000
[08:02:47][D][esp32.preferences:114]: Saving 1 preferences to flash...
[08:02:47][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed

```

and the success mode right after it


```
[08:03:23][D][cover:076]: 'Door' - Setting
[08:03:23][D][cover:084]:   Position: 0%
[08:03:23][D][ratgdo:533]: Close door called, current state: OPEN
[08:03:23][D][ratgdo:554]: Sending close door, current state: OPEN
[08:03:23][D][ratgdo:624]: Door command press: 00010100
[08:03:23][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010100
[08:03:23][D][ratgdo:285]: [105512] Encode for transmit rolling=0001ee0 fixed=0200006b2a data=01010080
[08:03:23][D][ratgdo:471]: Sending packet
[08:03:23][W][component:214]: Component api took a long time for an operation (0.07 s).
[08:03:23][W][component:215]: Components should block for at most 20-30ms.
[08:03:23][D][ratgdo:404]: Baud: 9615
[08:03:23][D][ratgdo:108]: [105666] received rolling=00182fa fixed=c0a3d2c00a data=000c01a1
[08:03:23][D][ratgdo:116]: cmd=0a1 (PAIR_3_RESP) byte2=00 byte1=0c nibble=1
[08:03:23][D][ratgdo:628]: Door command release: 00010000
[08:03:23][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010000
[08:03:23][D][ratgdo:285]: [105692] Encode for transmit rolling=0001ee0 fixed=0200006b2a data=01000080
[08:03:23][D][ratgdo:471]: Sending packet
[08:03:23][D][ratgdo:395]: Ignoring byte: F0, baud: 9615
[08:03:23][D][number:012]: 'Rolling code counter': Sending state 7905.000000
[08:03:24][D][ratgdo:404]: Baud: 9615
[08:03:24][D][ratgdo:108]: [106681] received rolling=00182fb fixed=c0a3d2c00a data=42600581
[08:03:24][D][ratgdo:116]: cmd=081 (STATUS) byte2=42 byte1=60 nibble=5
[08:03:24][D][ratgdo:257]: Schedule position sync: delta -1.000000, start position: 1.000000, start moving: 106694
[08:03:24][D][ratgdo:213]: Status: door=CLOSING light=ON lock=UNLOCKED
[08:03:24][D][ratgdo:275]: [106726] Position update: 0.998416
[08:03:24][D][cover:170]: 'Door' - Publishing:
```

**Comment by bdraco** [comment]
While this fixes the issue, and I think its fine for now, it would be better to understand why the GDO doesn't take the first close command.

**Comment by bdraco** [comment]
I've done ~25 cycles with this, and the problem is gone.

If we find a better solution we can revert this

**Comment by bdraco** [comment]
created https://github.com/ratgdo/esphome-ratgdo/issues/89 so we don't forget to revert this once we find the root cause

**Comment by mariusmuja** [comment]
I tried replicating this and it doesn't seem to happen on my gdo. Does the door need to be fully open to reproduce the issue, or the first close is ignored from any door position? How long do you need to wait after opening the door before attempting to close it?

This looks suspicious:
```
[08:03:23][D][ratgdo:108]: [105666] received rolling=00182fa fixed=c0a3d2c00a data=000c01a1
[08:03:23][D][ratgdo:116]: cmd=0a1 (PAIR_3_RESP) byte2=00 byte1=0c nibble=1
```
the `PAIR_3_RESP` received immediately after the second button press... Looks as if the GDO just "learned about"/"acknowledged" the presence of the esp and is starting to respond to it? Is a `PAIR_3_RESP` received every time the issue happens? Although if this is the cause (the GDO not recognizing the esp and requiring a button press/release to "pair") it doesn't explain why only a close command is ignored, should happen with open commands too...

**Comment by bdraco** [comment]
It only seems to happen on fully open.  It doesn't seem to matter how long it's been fully open.

If I stop it and close it it works fine.

**Comment by mariusmuja** [comment]
Is the `PAIR_3_RESP` message always received when the issue happens, or was that a coincidence?

**Comment by bdraco** [comment]
> the PAIR_3_RESP received immediately after the second button press... Looks as if the GDO just "learned about"/"acknowledged" the presence of the esp and is starting to respond to it? Is a PAIR_3_RESP received every time the issue happens? Although if this is the cause (the GDO not recognizing the esp and requiring a button press/release to "pair") it doesn't explain why only a close command is ignored, should happen with open commands too...


I need to test to see if it happens more than once after first reboot. I recall there was some commands removed from the first resync after boot. Maybe there is something some gdos need in that list

**Comment by bdraco** [comment]
> Is the `PAIR_3_RESP` message always received when the issue happens, or was that a coincidence?

Will check when I get home

**Comment by bdraco** [comment]
Happens multiple times so its not just once after reboot.  It does seem that `PAIR_3_RESP` is always send on the successful second call

first call

```

[13:54:02][D][cover:076]: 'Door' - Setting
[13:54:02][D][cover:084]:   Position: 0%
[13:54:02][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010100
[13:54:02][D][ratgdo:285]: [196821] Encode for transmit rolling=0001f53 fixed=0200006b2a data=01010080
[13:54:02][D][ratgdo:471]: Sending packet
[13:54:02][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010000
[13:54:02][D][ratgdo:285]: [196952] Encode for transmit rolling=0001f53 fixed=0200006b2a data=01000080
[13:54:02][D][ratgdo:471]: Sending packet
[13:54:02][D][number:012]: 'Rolling code counter': Sending state 8020.000000
[13:54:04][D][esp32.preferences:114]: Saving 1 preferences to flash...
[13:54:04][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed

```

second call

```

[13:54:14][D][cover:076]: 'Door' - Setting
[13:54:14][D][cover:084]:   Position: 0%
[13:54:14][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010100
[13:54:14][D][ratgdo:285]: [208861] Encode for transmit rolling=0001f54 fixed=0200006b2a data=01010080
[13:54:14][D][ratgdo:471]: Sending packet
[13:54:14][D][ratgdo:404]: Baud: 9615
[13:54:14][D][ratgdo:442]: Send command: DOOR_ACTION, data: 00010000
[13:54:14][D][ratgdo:285]: [208992] Encode for transmit rolling=0001f54 fixed=0200006b2a data=01000080
[13:54:14][D][ratgdo:471]: Sending packet
[13:54:14][D][ratgdo:108]: [209028] received rolling=0018354 fixed=c0a3d2c00a data=000c01a1
[13:54:14][D][ratgdo:116]: cmd=0a1 (PAIR_3_RESP) byte2=00 byte1=0c nibble=1
[13:54:14][D][number:012]: 'Rolling code counter': Sending state 8021.000000
[13:54:15][D][ratgdo:404]: Baud: 9615
[13:54:15][D][ratgdo:108]: [210030] received rolling=0018355 fixed=c0a3d2c00a data=42600581
[13:54:15][D][ratgdo:116]: cmd=081 (STATUS) byte2=42 byte1=60 nibble=5
[13:54:15][D][ratgdo:257]: Schedule position sync: delta -1.000000, start position: 1.000000, start moving: 210042
[13:54:15][D][ratgdo:213]: Status: door=CLOSING light=ON lock=UNLOCKED
[13:54:15][D][ratgdo:275]: [210073] Position update: 0.998465
[13:54:15][D][cover:170]: 'Door' - Publishing:
[13:54:15][D][cover:173]:   Position: 100%
[13:54:15][D][cover:186]:   Current Operation: CLOSING
[13:54:16][D][ratgdo:275]: [210580] Position update: 0.973366
```

**Comment by bdraco** [comment]
I also see this when its finishing opening

```
:186]:   Current Operation: OPENING
[13:55:37][D][ratgdo:275]: [291476] Position update: 0.917861
[13:55:37][D][cover:170]: 'Door' - Publishing:
[13:55:37][D][cover:173]:   Position: 92%
[13:55:37][D][cover:186]:   Current Operation: OPENING
[13:55:37][D][ratgdo:404]: Baud: 9615
[13:55:37][D][ratgdo:108]: [291814] received rolling=0018358 fixed=c4a3d2c00a data=b004010a
[13:55:37][D][ratgdo:116]: cmd=40a (TTC) byte2=b0 byte1=04 nibble=1
[13:55:37][D][ratgdo:404]: Baud: 9615
[13:55:37][D][ratgdo:108]: [291895] received rolling=0018359 fixed=c0a3d2c00a data=000001a0
[13:55:37][D][ratgdo:116]: cmd=0a0 (PAIR_3) byte2=00 byte1=00 nibble=1
[13:55:37][D][ratgdo:404]: Baud: 9615
[13:55:37][D][ratgdo:108]: [291975] received rolling=001835a fixed=c0a3d2c00a data=000201a1
[13:55:37][D][ratgdo:116]: cmd=0a1 (PAIR_3_RESP) byte2=00 byte1=02 nibble=1
[13:55:37][D][ratgdo:275]: [291996] Position update: 0.945668
[13:55:37][D][cover:170]: 'Door' - Publishing:
[13:55:37][D][cover:173]:   Position: 95%
[13:55:37][D][cover:186]:   Current Operation: OPENING
[13:55:37][D][ratgdo:404]: Baud: 9900
[13:55:37][D][ratgdo:108]: [292061] received rolling=00034c0 fixed=40515ca90c data=000101a1
[13:55:37][D][ratgdo:116]: cmd=0a1 (PAIR_3_RESP) byte2=00 byte1=01 nibble=1
[13:55:37][D][ratgdo:404]: Baud: 9615
[13:55:37][D][ratgdo:108]: [292125] received rolling=001835a fixed=c0a3d2c00a data=000201a1
[13:55:37][D][ratgdo:116]: cmd=0a1 (PAIR_3_RESP) byte2=00 byte1=02 nibble=1
[13:55:38][D][ratgdo:275]: [292501] Position update: 0.972674
[13:55:38][D][cover:170]: 'Door' - Publishing:
[13:55:38][D][cover:173]:   Position: 97%
[13:55:38][D][cover:186]:   Current Operation: OPENING
[13:55:38][D][ratgdo:404]: Baud: 9615
[13:55:38][D][ratgdo:108]: [292831] received rolling=001835b fixed=c0a3d2c00a data=42600181
[13:55:38][D][ratgdo:116]: cmd=081 (STATUS) byte2=42 byte1=60 nibble=1
[13:55:38][D][ratgdo:606]: Cancelling position callbacks
[13:55:38][D][ratgdo:213]: Status: door=OPEN light=ON lock=UNLOCKED
[13:55:38][D][cover:170]: 'Door' - Publishing:
[13:55:38][D][cover:173]:   Position: 100%
[13:55:38][D][cover:186]:   Current Operation: IDLE
[13:55:38][D][switch:012]: 'Status door' Turning ON.
[13:55:38][D][switch:055]: 'Status door': Sending state ON
```

**Comment by bdraco** [comment]
I think its the client id change. I think the random value is too high

**Comment by mariusmuja** [comment]
> Happens multiple times so its not just once after reboot. It does seem that PAIR_3_RESP is always sent on the successful second call

I'm pretty sure this is related to the issue. I wonder if there's some limit of devices that the GDO talks to and the esp is "competing" with the wall button. Can you disconnect the wall button from the wires and see if the problem stops?

**Comment by bdraco** [comment]
The random value it choose was 27,434.0

**Comment by bdraco** [comment]
I changed the value to 35000 and its all working now though 🙈

**Comment by bdraco** [comment]
I reflashed it as well to see if I could get it to happen again and its still not happening now

**Comment by bdraco** [comment]
I switched it back to 27,434.0 and the problem comes back

**Comment by mariusmuja** [comment]
I remember when I replaced my GDO I connected two wall buttons to the line for a while and occasionally one button or the other would require double presses to work. I didn't think much of it at the time, but now it seems like the same issue. Maybe there can be a single wall button recognized by the GDO at a time and a wall button is recognized as certain pattern for remote_id (maybe there's a bit/bits part of the remote_id that's set for wall buttons?)

**Comment by bdraco** [comment]
> I remember when I replaced my GDO I connected two wall buttons to the line for a while and occasionally one button or the other would require double presses to work. I didn't think much of it at the time, but now it seems like the same issue. Maybe there can be a single wall button recognized by the GDO at a time and a wall button is recognized as certain pattern for remote_id (maybe there's a bit/bits part of the remote_id that's set for wall buttons?)

Yeah, it seems like there are some bits we can't see for the id or the problem happens....

**Comment by mariusmuja** [comment]
You could take `27434` and start flipping bits to find out which one... :)

**Comment by bdraco** [comment]
## Has issue

```
bin(27434)
'0b110101100101010'
```

## Does not have issue

```
bin(27432)
'0b110101100101000'
bin(27433)
'0b110101100101001'
bin(1335) - original code
'0b10100110111'
bin(25000)
'0b110000110101000'
bin(311)
'0b100110111'
``````

I haven't found another id with the issue yet ...

**Comment by bdraco** [comment]
@jfroy Can you post your random client id?

**Comment by bdraco** [comment]
I haven't found any pattern here...

**Comment by bdraco** [comment]
Just confirmed again that switching back to 27434 is reliably a problem

I'm going to try that id with another. GDO

**Comment by bdraco** [comment]
Switching another GDO to 27434 recreated the issue on that so at least we know what triggers it.. but not why

**Comment by bdraco** [comment]
@PaulWieland any thoughts?

**Comment by jfroy** [comment]
> @jfroy Can you post your random client id?

37006

**Comment by mariusmuja** [comment]
Confirming remote_id 27434 is causing issues on my GDO as well. It seems to be a conflict between the wall button and esp, for example I can toggle the light from HA many times, but as soon as I toggle it from the wall button (or the wall button reports motion), I need to flip the light toggle twice in HA for it to work. 

My current theory is still that 27434 is recognized as a wall button and apparently when it comes to wall buttons "there can be only one"...

**Comment by bdraco** [comment]
Awesome 37006 causes the problem for me as well

**Comment by PaulWieland** [comment]
I haven't personally encountered this problem with the mqtt version nor has anyone reported it on the mqtt repo, so I'm wondering what the differences could be.

Two things come to mind... the startup sync sequence of commands and the non standard length low/high at the start of each message. In the early days of the firmware I experimented with the length of the low/high but the door wouldn't always respond. 

I also tried pairing the list of sync commands down but wound up with weird behaviors so I stuck to the same startup sequence that the wall panels have and it's been reliable.

If I have some time I'll do some signal comparisons between the two.

**Comment by PaulWieland** [comment]
> Confirming remote_id 27434 is causing issues on my GDO as well. It seems to be a conflict between the wall button and esp, for example I can toggle the light from HA many times, but as soon as I toggle it from the wall button (or the wall button reports motion), I need to flip the light toggle twice in HA for it to work.
> 
> My current theory is still that 27434 is recognized as a wall button and apparently when it comes to wall buttons "there can be only one"...

I have to find it in the manual, but I think they officially support multiple wall buttons per GDO (at least on the model I was researching).

**Comment by bdraco** [comment]
Unfortunately I don't see the pattern between the two non-working ids

**Comment by jfroy** [comment]
Maybe it's not specific bits but combinations of bits or a checksum or parity type of check. Seems potentially gnarly to reverse engineer.

**Comment by bdraco** [comment]
Anything with `0xA` is an issue

**Comment by mariusmuja** [comment]
Here's the pattern I got so far:

```
is_bad_remote_id = (remote_id & 0x403) == 2;
```
essentially, bit 11==0, bit1==1 and bit0 ==0

**Comment by bdraco** [comment]
Maybe the client_id/remote_id is supposed to be shifted to few bits to the left?

**Comment by mariusmuja** [comment]
> Maybe the client_id/remote_id is supposed to be shifted to few bits to the left?

That might be enough to solve the issue for us.

I thought for a while that all remote_ids ending in `0b10` have the issue, then I found `65534` which doesn't have it, so there's more (bits) than that.... but avoiding `0b10` ending remote_ids might be enough.

**Pull request merged**
