### PR TITLE
base: add uptime sensor

### PR DESCRIPTION
**Pull request by visigoth**
An uptime sensor is a nice-to-have debugging facility as it lets me verify that ratgdo is getting consistent power when using a voltage regulator connected to the battery backup terminals of my garage door opener.

### CODE REVIEW

**Comment by visigoth** [comment]
I tested this with `esphome run v25iboard.yaml` and saw the uptime sensor in the table on the device's web page.

**Comment by bdraco** [comment]
Uptime sensors are generally not enabled by default and usually only for debugging as they create many state updates and fill up Home Assistant's database quickly.

**Comment by visigoth** [comment]
didn't know that; is there a way to have HA ignore it?

**Comment by ccutrer** [comment]
You could set `disabled_by_default: true` in the ESPHome YAML, then a user would have to explicitly enable it in Home Assistant.

**Comment by bdraco** [comment]
@visigoth Thanks for your PR. Because of the concern above https://github.com/ratgdo/esphome-ratgdo/pull/281#issuecomment-2132604433 , I think we should not add this to the default config.  Instead it would be nice to have a documentation PR on how to add it manually.

Thanks

**Pull request closed without merging**
