### PR TITLE
Convert lock remotes switch to a lock component

### LINKED ISSUE #131: Lock instead of switch for "lock remotes"?
It makes more sense for me for esphome to export a lock component rather than a switch for the toggle to "lock remotes".  Changing the switch in Home Assistant to a lock doesn't work right as it needs to be inverted.

### PR DESCRIPTION
**Pull request by mariusmuja**
## Breaking change

The lock remotes switch has been replaced with a lock entity.  The old switch will need to be manually removed in Home Assistant after upgrading the firmware on the ESP.

Fixes #131.

### CODE REVIEW

**Comment by bdraco** [comment]
Screenshot 2023-12-05 at 2 07 02 PM

**Comment by bdraco** [comment]
Thanks @mariusmuja

**Review by bdraco — APPROVED** [review]

**Comment by jshatch** [comment]
Can we maybe add the switch component back *as well* as the lock component rather than kill one for the other?  It was working great for me as a switch, but getting the lock component to work has proven problematic in openHAB.

**Comment by mariusmuja** [comment]
You can always add a switch to the yaml file and flip in the lock's `on_lock` and `on_unlock` actions, for example:

```
switch:
  - platform: template
    id: ${id_prefix}_lock_remotes_switch
    name: "Lock remotes switch"
    optimistic: true

lock:
  - platform: ratgdo
    id: ${id_prefix}_lock_remotes
    ratgdo_id: ${id_prefix}
    name: "Lock remotes"
    on_lock:
      - switch.turn_on: ${id_prefix}_lock_remotes_switch
    on_unlock:
      - switch.turn_off: ${id_prefix}_lock_remotes_switch
```

**Comment by jshatch** [comment]
Finally got around to trying your suggestion and with a slight modification it works fine for my use case.  Instead of the lock controlling the switch I wanted the switch to control the lock.
```
switch:
  - platform: template
    id: ${id_prefix}_lock_remotes_switch
    name: "Lock remotes switch"
    on_turn_on:
      - lock.lock: ${id_prefix}_lock_remotes
    on_turn_off:
      - lock.unlock: ${id_prefix}_lock_remotes
    optimistic: true
...
```
Right now I'm running this off my own fork, do you want a PR or is this not something you would want in the mainline code?

**Pull request merged**
