### PR TITLE
Lolin s2 mini support

### PR DESCRIPTION
**Pull request by rako77**
This PR aims to add support for the Lolin s2 min (https://www.wemos.cc/en/latest/s2/s2_mini.html)

It has been tested and works with my garage door.

As described in issue #52

Caveat:
Flashing from the web installer doesn't work for me however the web interface does allow for setting up the wifi once the board is flashed.
To flash manually I followed theses steps: https://community.home-assistant.io/t/esp32-s2-and-esphome-upload/382885/18

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
Lgtm

**Comment by bdraco** [comment]
Thanks @rako77

**Comment by bdraco** [comment]
Looks like the image link needs to be fixed up as it's broken on the web installer page

**Comment by rako77** [comment]
> Looks like the image link needs to be fixed up as it's broken on the web installer page

I'll submit a fix soon

**Pull request merged**
